version: 2
jobs:
   build:
     environmnt:
       IMAGE_NAME: mukuntharya2022/gosimple
     docker:
       - image: circleci/buildpack-deps:stretch
     steps:
       - checkout
       - setup_remote_docker
       - run:
           name: Build docker image
           command: docker build -t  $IMAGE_NAME:latest .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master