---
version: 2
jobs:
   build:
     environmnt:
       IMAGE_NAME: mukuntharya2022/gosimple
     docker:
       - image: circleci/buildpack-deps:stretch
     steps:
       - checkout
       - setup_remote_docker
       - run:
           name: Build docker image
           command: docker build -t  mukuntharya2022/gosimple:latest .
   publish-latest:
     environment:
       IMAGE_NAME: mukuntharya2022/gosimple:latest
     docker:
       - image: circleci/buildpack-deps:stretch
     steps:
       - setup_remote_docker
       - run:
           name: Publish image to docker hub
           command: 
             
             docker push mukuntharya2022/gosimple:lates
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
...
