---
version: 2.1
executors:
  docker-publisher: 
    environment:
      Image_name: mukuntharya2022/gosimple
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executors: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
             docker build -t $Image_name:v1 .
      - run: 
          name: Archive Docker image
          command: docker save -o image.tar $image_name
   
  publish-latest:
     executors: docker-publisher
     steps:
       - attach_workspace:
           at: /tmp/workspace
       - setup_remote_worker
       - run: 
           name: Load Archived image  
           command: docker load -i /tmp/workspace/image.tar
       - run: 
           name: Publish Docker Image  to Docker Hub
           command: | 
             echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
             docker push $IMAGE_NAME:v1

workflows:
  version: 2
  build-master:
    jobs: 
      - build:
          filters:
            branches:
              only: master
      - publish: latest
          requires:
            - build
          filters:
            branches:
              only: master


             
