version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: mukuntharya2022/gosimple
      DOCKERHUB_PASS: mukunth@1996
      DOCKERHUB_USERNAME: mukuntharya2022
    docker:
      - image: circleci/golang:1.18
      - image: ciecleci/buidpack-deps:stretch

jobs:
  build:
    
    executor: docker-publisher
    working_directory: /home/mukunth/circleci
    steps: 
      - checkout
      - run: go test
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker build -t $IMAGE_NAME:v2 .
      - run:
          name: archive the docker image
          command: docker save -o myimage.tar $IMAGE_NAME
          
      - persists_to_workspace:
          root: .
          paths: 
            - ./myimage.tar
       
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
            
      - setup_remote_docker
      - run: 
          name: Load Saved file
          command: docker load -i /tmp/workspace/myimage.tar
            
      - run:
          name: publish image to docker hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --pasword-stdin
            docker push $IMAGE_NAME:v2
            
workflows:
  version: 2
  build-master:
    jobs:
    - build:
        filters:
          branches:
            only: masters
    - publish-latest:
        requires:
          - build
        filters:
          branches:
            only: master
